logging:
  enabled: true
  path: "logs/easygpt.jsonl"

models:
  default_provider: openai
  providers:
    openai:
      - gpt-4o-mini
      - gpt-5-mini
    gemini:
      - gemini-1.5-flash
    deepseek:
      - deepseek-chat
    mock:
      - mock-model

